### ISSUE TITLE
[QUESTION] Encoding used as dependency ?

### ISSUE THREAD

**Issue by fraxken** [npm/minipass-fetch#10]
# What / Why
The dependency encoding appear as dependency and optionalDependencies whereas it seems to be used only in the tests.

# Expected
It should be tagged as devDependencies (but maybe i miss something).

**Comment by isaacs** [comment]
It's an optional dependency that is used here: https://github.com/npm/arborist/security/advisories/GHSA-2h3h-q99f-3fhc
