### ISSUE TITLE
[BUG] minipass-fetch is not aware of NODE_TLS_REJECT_UNAUTHORIZED

### ISSUE THREAD

**Issue by svennergr** [npm/minipass-fetch#11]
The `rejectUnauthorized` property is fixed to `true` if it is not set. This will not respect the setting of the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable.
 
https://github.com/npm/minipass-fetch/blob/bbb9132459bb1157244542a4df8b50f9cdca5330/lib/request.js#L84

**Comment by isaacs** [comment]
Fixed by #12
